import 'package:flutter/material.dart';

class AppColors {
  static const ColorScheme light = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF000000),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFF276EF1),
    onPrimaryContainer: Color(0xFFFFFFFF),
    secondary: Color(0xFF276EF1),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFE8EFF8),
    onSecondaryContainer: Color(0xFF276EF1),
    tertiary: Color(0xFF05A357),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFE0F5EA),
    onTertiaryContainer: Color(0xFF05A357),
    surface: Color(0xFFFFFFFF),
    onSurface: Color(0xFF000000),
    onSurfaceVariant: Color(0xFF6B6B6B),
    surfaceContainerHighest: Color(0xFFF6F6F6),
    surfaceContainerHigh: Color(0xFFF9F9F9),
    surfaceContainer: Color(0xFFFCFCFC),
    error: Color(0xFFE11900),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFDE8E5),
    onErrorContainer: Color(0xFFE11900),
    outline: Color(0xFFE2E2E2),
    outlineVariant: Color(0xFFF6F6F6),
  );

  static const ColorScheme dark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFFFFFFF),
    onPrimary: Color(0xFF000000),
    primaryContainer: Color(0xFF276EF1),
    onPrimaryContainer: Color(0xFFFFFFFF),
    secondary: Color(0xFF5B91F4),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFF1A1A1A),
    onSecondaryContainer: Color(0xFF5B91F4),
    tertiary: Color(0xFF3ECC8B),
    onTertiary: Color(0xFF000000),
    tertiaryContainer: Color(0xFF1A1A1A),
    onTertiaryContainer: Color(0xFF3ECC8B),
    surface: Color(0xFF000000),
    onSurface: Color(0xFFFFFFFF),
    onSurfaceVariant: Color(0xFF999999),
    surfaceContainerHighest: Color(0xFF222222),
    surfaceContainerHigh: Color(0xFF1A1A1A),
    surfaceContainer: Color(0xFF111111),
    error: Color(0xFFFF6B5E),
    onError: Color(0xFF000000),
    errorContainer: Color(0xFF1A1A1A),
    onErrorContainer: Color(0xFFFF6B5E),
    outline: Color(0xFF333333),
    outlineVariant: Color(0xFF222222),
  );

  static const ColorScheme helloKitty = ColorScheme(
    brightness: Brightness.light,

    // Розовый — основной
    primary: Color(0xFFE84B8A),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFFFD1E3),
    onPrimaryContainer: Color(0xFFE84B8A),

    // Красный бантик
    secondary: Color(0xFFE53935),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFFFCDD2),
    onSecondaryContainer: Color(0xFFE53935),

    // Лавандовый
    tertiary: Color(0xFFA678DE),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFF0E0FF),
    onTertiaryContainer: Color(0xFFA678DE),

    // Поверхности — нежно-розовый
    surface: Color(0xFFFFF0F5),
    onSurface: Color(0xFF4A2040),
    onSurfaceVariant: Color(0xFF9E7A91),
    surfaceContainerHighest: Color(0xFFFFE4EE),
    surfaceContainerHigh: Color(0xFFFFEAF2),
    surfaceContainer: Color(0xFFFFF0F6),

    // Ошибки
    error: Color(0xFFE53935),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFCDD2),
    onErrorContainer: Color(0xFFE53935),

    // Обводки
    outline: Color(0xFFF8BBD0),
    outlineVariant: Color(0xFFFFE4EE),
  );

    // 🤓 Hacker / Matrix
  static const ColorScheme hacker = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF00FF41),
    onPrimary: Color(0xFF000000),
    primaryContainer: Color(0xFF003B00),
    onPrimaryContainer: Color(0xFF00FF41),
    secondary: Color(0xFF00FF41),
    onSecondary: Color(0xFF000000),
    secondaryContainer: Color(0xFF002200),
    onSecondaryContainer: Color(0xFF00FF41),
    tertiary: Color(0xFF00CC33),
    onTertiary: Color(0xFF000000),
    tertiaryContainer: Color(0xFF002200),
    onTertiaryContainer: Color(0xFF00CC33),
    surface: Color(0xFF0A0A0A),
    onSurface: Color(0xFF00FF41),
    onSurfaceVariant: Color(0xFF00AA2A),
    surfaceContainerHighest: Color(0xFF0F1A0F),
    surfaceContainerHigh: Color(0xFF0D150D),
    surfaceContainer: Color(0xFF0B100B),
    error: Color(0xFFFF0000),
    onError: Color(0xFF000000),
    errorContainer: Color(0xFF1A0000),
    onErrorContainer: Color(0xFFFF0000),
    outline: Color(0xFF004D00),
    outlineVariant: Color(0xFF002200),
  );

  // 👾 Vaporwave
  static const ColorScheme vaporwave = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFFF71CE),
    onPrimary: Color(0xFF1A0011),
    primaryContainer: Color(0xFF4D0033),
    onPrimaryContainer: Color(0xFFFF71CE),
    secondary: Color(0xFF01CDFE),
    onSecondary: Color(0xFF001A22),
    secondaryContainer: Color(0xFF003344),
    onSecondaryContainer: Color(0xFF01CDFE),
    tertiary: Color(0xFFB967FF),
    onTertiary: Color(0xFF1A0033),
    tertiaryContainer: Color(0xFF2D004D),
    onTertiaryContainer: Color(0xFFB967FF),
    surface: Color(0xFF0D0221),
    onSurface: Color(0xFFFF71CE),
    onSurfaceVariant: Color(0xFF9B59B6),
    surfaceContainerHighest: Color(0xFF1A0A2E),
    surfaceContainerHigh: Color(0xFF150828),
    surfaceContainer: Color(0xFF110525),
    error: Color(0xFFFF6B6B),
    onError: Color(0xFF1A0000),
    errorContainer: Color(0xFF330000),
    onErrorContainer: Color(0xFFFF6B6B),
    outline: Color(0xFF4A1942),
    outlineVariant: Color(0xFF2D0D28),
  );

  // 🌸 Sakura
  static const ColorScheme sakura = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFFD4578B),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFFFE0EC),
    onPrimaryContainer: Color(0xFFD4578B),
    secondary: Color(0xFF7BAE7F),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFDFF0E0),
    onSecondaryContainer: Color(0xFF5A8A5E),
    tertiary: Color(0xFF8B7355),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFF0E6D8),
    onTertiaryContainer: Color(0xFF8B7355),
    surface: Color(0xFFFFF8FA),
    onSurface: Color(0xFF3D2C35),
    onSurfaceVariant: Color(0xFF8C7A84),
    surfaceContainerHighest: Color(0xFFFFF0F4),
    surfaceContainerHigh: Color(0xFFFFF4F7),
    surfaceContainer: Color(0xFFFFF8FA),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFDAD6),
    onErrorContainer: Color(0xFFBA1A1A),
    outline: Color(0xFFEDD5DE),
    outlineVariant: Color(0xFFFFF0F4),
  );

  // 🐸 Pepe
  static const ColorScheme pepe = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF629A40),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFD4EDBC),
    onPrimaryContainer: Color(0xFF3D6B22),
    secondary: Color(0xFFA67C52),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFFFDCC2),
    onSecondaryContainer: Color(0xFF8B5E35),
    tertiary: Color(0xFF5C7CFA),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFDBE4FF),
    onTertiaryContainer: Color(0xFF5C7CFA),
    surface: Color(0xFFF5F9F0),
    onSurface: Color(0xFF2D3A22),
    onSurfaceVariant: Color(0xFF6B7A5E),
    surfaceContainerHighest: Color(0xFFE8F0DE),
    surfaceContainerHigh: Color(0xFFEEF5E5),
    surfaceContainer: Color(0xFFF2F8EA),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFDAD6),
    onErrorContainer: Color(0xFFBA1A1A),
    outline: Color(0xFFCCDDBF),
    outlineVariant: Color(0xFFE8F0DE),
  );

  // 🌊 Ocean
  static const ColorScheme ocean = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF64FFDA),
    onPrimary: Color(0xFF00332B),
    primaryContainer: Color(0xFF004D40),
    onPrimaryContainer: Color(0xFF64FFDA),
    secondary: Color(0xFF80DEEA),
    onSecondary: Color(0xFF003640),
    secondaryContainer: Color(0xFF004D5A),
    onSecondaryContainer: Color(0xFF80DEEA),
    tertiary: Color(0xFF82B1FF),
    onTertiary: Color(0xFF002966),
    tertiaryContainer: Color(0xFF003D99),
    onTertiaryContainer: Color(0xFF82B1FF),
    surface: Color(0xFF0A1929),
    onSurface: Color(0xFFE0F7FA),
    onSurfaceVariant: Color(0xFF5F8A96),
    surfaceContainerHighest: Color(0xFF132F4C),
    surfaceContainerHigh: Color(0xFF0F2740),
    surfaceContainer: Color(0xFF0C2035),
    error: Color(0xFFFF8A80),
    onError: Color(0xFF330000),
    errorContainer: Color(0xFF4D0000),
    onErrorContainer: Color(0xFFFF8A80),
    outline: Color(0xFF1E4976),
    outlineVariant: Color(0xFF132F4C),
  );

  // 🎃 Halloween
  static const ColorScheme halloween = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFFF9800),
    onPrimary: Color(0xFF1A0F00),
    primaryContainer: Color(0xFF4D2E00),
    onPrimaryContainer: Color(0xFFFF9800),
    secondary: Color(0xFFAB47BC),
    onSecondary: Color(0xFF1A0022),
    secondaryContainer: Color(0xFF380044),
    onSecondaryContainer: Color(0xFFAB47BC),
    tertiary: Color(0xFF66BB6A),
    onTertiary: Color(0xFF003300),
    tertiaryContainer: Color(0xFF1B5E20),
    onTertiaryContainer: Color(0xFF66BB6A),
    surface: Color(0xFF1A0F00),
    onSurface: Color(0xFFFFE0B2),
    onSurfaceVariant: Color(0xFF997A4D),
    surfaceContainerHighest: Color(0xFF2D1A00),
    surfaceContainerHigh: Color(0xFF261500),
    surfaceContainer: Color(0xFF201100),
    error: Color(0xFFFF5252),
    onError: Color(0xFF1A0000),
    errorContainer: Color(0xFF330000),
    onErrorContainer: Color(0xFFFF5252),
    outline: Color(0xFF4D3319),
    outlineVariant: Color(0xFF33220D),
  );

  // 🐕 Doge
  static const ColorScheme doge = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFFBA8C3C),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFFFF3D6),
    onPrimaryContainer: Color(0xFF8B6914),
    secondary: Color(0xFFE57373),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFFFCDD2),
    onSecondaryContainer: Color(0xFFC62828),
    tertiary: Color(0xFF4DB6AC),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFB2DFDB),
    onTertiaryContainer: Color(0xFF00695C),
    surface: Color(0xFFFFFDE7),
    onSurface: Color(0xFF4E3A1A),
    onSurfaceVariant: Color(0xFF8C7A55),
    surfaceContainerHighest: Color(0xFFFFF8E1),
    surfaceContainerHigh: Color(0xFFFFFBEB),
    surfaceContainer: Color(0xFFFFFDE7),
    error: Color(0xFFD32F2F),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFCDD2),
    onErrorContainer: Color(0xFFD32F2F),
    outline: Color(0xFFE6D5A8),
    outlineVariant: Color(0xFFFFF3D6),
  );
}
