import 'package:flutter/material.dart';

class AppColors {
  static const ColorScheme light = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF000000),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFF276EF1),
    onPrimaryContainer: Color(0xFFFFFFFF),
    secondary: Color(0xFF276EF1),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFE8EFF8),
    onSecondaryContainer: Color(0xFF276EF1),
    tertiary: Color(0xFF05A357),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFE0F5EA),
    onTertiaryContainer: Color(0xFF05A357),
    surface: Color(0xFFFFFFFF),
    onSurface: Color(0xFF000000),
    onSurfaceVariant: Color(0xFF6B6B6B),
    surfaceContainerHighest: Color(0xFFF6F6F6),
    surfaceContainerHigh: Color(0xFFF9F9F9),
    surfaceContainer: Color(0xFFFCFCFC),
    error: Color(0xFFE11900),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFDE8E5),
    onErrorContainer: Color(0xFFE11900),
    outline: Color(0xFFE2E2E2),
    outlineVariant: Color(0xFFF6F6F6),
  );

  static const ColorScheme dark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFFFFFFF),
    onPrimary: Color(0xFF000000),
    primaryContainer: Color(0xFF276EF1),
    onPrimaryContainer: Color(0xFFFFFFFF),
    secondary: Color(0xFF5B91F4),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFF1A1A1A),
    onSecondaryContainer: Color(0xFF5B91F4),
    tertiary: Color(0xFF3ECC8B),
    onTertiary: Color(0xFF000000),
    tertiaryContainer: Color(0xFF1A1A1A),
    onTertiaryContainer: Color(0xFF3ECC8B),
    surface: Color(0xFF000000),
    onSurface: Color(0xFFFFFFFF),
    onSurfaceVariant: Color(0xFF999999),
    surfaceContainerHighest: Color(0xFF222222),
    surfaceContainerHigh: Color(0xFF1A1A1A),
    surfaceContainer: Color(0xFF111111),
    error: Color(0xFFFF6B5E),
    onError: Color(0xFF000000),
    errorContainer: Color(0xFF1A1A1A),
    onErrorContainer: Color(0xFFFF6B5E),
    outline: Color(0xFF333333),
    outlineVariant: Color(0xFF222222),
  );
}
